/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.glavna;

import domain.User;
import forme.gost.FrmPretragaGosta;
import forme.gost.FrmUnosGosta;
import forme.racun.FrmRacun;
import forme.sjedinica.FrmPretragaSJedinica;
import forme.sjedinica.FrmUnosNoveSJedinice;
import javax.swing.JDialog;

/**
 *
 * @author marij
 */
public class FrmGlavna extends javax.swing.JFrame {


    /**
     * Creates new form FrmMain
     */
    public FrmGlavna() {
        initComponents();
        setScreenCenter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        jmbMainMenu = new javax.swing.JMenuBar();
        menuGost = new javax.swing.JMenu();
        MenuItemUnosNovogGosta = new javax.swing.JMenuItem();
        MenuItemPretragaGostiju = new javax.swing.JMenuItem();
        MenuItemKreiranjeRacuna = new javax.swing.JMenuItem();
        menuSJedinica = new javax.swing.JMenu();
        menuItemUnosSJ = new javax.swing.JMenuItem();
        menuItemPretragaSJ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Softverski sistem za hotel u Javi");

        menuGost.setText("Gost");

        MenuItemUnosNovogGosta.setText("Unos novog gosta");
        MenuItemUnosNovogGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUnosNovogGostaActionPerformed(evt);
            }
        });
        menuGost.add(MenuItemUnosNovogGosta);

        MenuItemPretragaGostiju.setText("Pretraga gostiju");
        MenuItemPretragaGostiju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPretragaGostijuActionPerformed(evt);
            }
        });
        menuGost.add(MenuItemPretragaGostiju);

        MenuItemKreiranjeRacuna.setText("Kreiranje racuna");
        MenuItemKreiranjeRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemKreiranjeRacunaActionPerformed(evt);
            }
        });
        menuGost.add(MenuItemKreiranjeRacuna);

        jmbMainMenu.add(menuGost);

        menuSJedinica.setText("Smestajne jedinice");

        menuItemUnosSJ.setText("Unos nove smestajne jedinice");
        menuItemUnosSJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUnosSJActionPerformed(evt);
            }
        });
        menuSJedinica.add(menuItemUnosSJ);

        menuItemPretragaSJ.setText("Pretraga smestajnih jedinica");
        menuItemPretragaSJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaSJActionPerformed(evt);
            }
        });
        menuSJedinica.add(menuItemPretragaSJ);

        jmbMainMenu.add(menuSJedinica);

        setJMenuBar(jmbMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemUnosNovogGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUnosNovogGostaActionPerformed
        JDialog frmUnosGosta= new FrmUnosGosta(this, true, FrmMode.NEW,null);
  
  frmUnosGosta.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemUnosNovogGostaActionPerformed

    private void MenuItemPretragaGostijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPretragaGostijuActionPerformed
         JDialog frmPretraga= new FrmPretragaGosta(this, true,FrmMode.EDIT);
  
            frmPretraga.setVisible(true);
    }//GEN-LAST:event_MenuItemPretragaGostijuActionPerformed

    private void MenuItemKreiranjeRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemKreiranjeRacunaActionPerformed
            JDialog frmRacun= new FrmRacun(this, true);
  
  frmRacun.setVisible(true);
    
    }//GEN-LAST:event_MenuItemKreiranjeRacunaActionPerformed

    private void menuItemUnosSJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUnosSJActionPerformed
         JDialog frmUnosSJ= new FrmUnosNoveSJedinice(this, true);
  
  frmUnosSJ.setVisible(true);
    }//GEN-LAST:event_menuItemUnosSJActionPerformed

    private void menuItemPretragaSJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretragaSJActionPerformed
            JDialog frmPretragaSJ= new FrmPretragaSJedinica(this, true);
  
            frmPretragaSJ.setVisible(true);
    }//GEN-LAST:event_menuItemPretragaSJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemKreiranjeRacuna;
    private javax.swing.JMenuItem MenuItemPretragaGostiju;
    private javax.swing.JMenuItem MenuItemUnosNovogGosta;
    private javax.swing.JMenuBar jmbMainMenu;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenu menuGost;
    private javax.swing.JMenuItem menuItemPretragaSJ;
    private javax.swing.JMenuItem menuItemUnosSJ;
    private javax.swing.JMenu menuSJedinica;
    // End of variables declaration//GEN-END:variables

    void setUser(User user) {
      lblUser.setText(user.getFirstname()+" "+user.getLastname());
    }
     private void setScreenCenter() {
        setLocationRelativeTo(null);
    }
}
