/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.gost;

import domain.Gost;
import forme.glavna.FrmMode;
import forme.gost.model.ModelTabeleGosti;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import kontroler.Kontroler;
import kontroler.gost.KontrolerBrisanjeGosta;
import kontroler.gost.KontrolerPretragaGostiju;
import kontroler.racun.KontrolerRacuna;

/**
 *
 * @author marij
 */
public class FrmPretragaGosta extends javax.swing.JDialog {

    /**
     * Creates new form FrmPretragaGosta
     */
    KontrolerRacuna kontrolerR;
    KontrolerPretragaGostiju kontrolerP;
    KontrolerBrisanjeGosta kontrolerB;
    public FrmPretragaGosta(java.awt.Frame parent, boolean modal, FrmMode mode) {
        super(parent, modal);
        initComponents();
      //  dodajModelTabele();
        //srediFormu();
        srediFormu(mode);
        kontrolerP= new KontrolerPretragaGostiju();
        kontrolerP.srediFormu(this);
        kontrolerB=new KontrolerBrisanjeGosta();
        setScreenCenter();
    
    }
public FrmPretragaGosta(boolean modal, FrmMode mode){
    initComponents();
      //  dodajModelTabele();
        //srediFormu();
        srediFormu(mode);
        kontrolerP= new KontrolerPretragaGostiju();
        kontrolerP.srediFormu(this);
       // kontrolerB=new KontrolerBrisanjeGosta();
}
    public JTable getTblGosti() {
        return tblGosti;
    }

    public JTextField getTxtKriterujum() {
        return txtKriterujum;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtKriterujum = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        panelZaNestajanje = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGosti = new javax.swing.JTable();
        btnPrikaziSve = new javax.swing.JButton();
        btnJMBG = new javax.swing.JRadioButton();
        btnImePrezime = new javax.swing.JRadioButton();
        btnIzmeni = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        btnIzbrisi = new javax.swing.JButton();
        btnIzaberi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga gostiju");

        jLabel1.setText("Kriterijum pretrage: ");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblGosti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGosti);

        btnPrikaziSve.setText("Prikazi sve");
        btnPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelZaNestajanjeLayout = new javax.swing.GroupLayout(panelZaNestajanje);
        panelZaNestajanje.setLayout(panelZaNestajanjeLayout);
        panelZaNestajanjeLayout.setHorizontalGroup(
            panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZaNestajanjeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikaziSve, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelZaNestajanjeLayout.setVerticalGroup(
            panelZaNestajanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelZaNestajanjeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrikaziSve)
                .addContainerGap())
        );

        buttonGroup1.add(btnJMBG);
        btnJMBG.setText("JMBG");

        buttonGroup1.add(btnImePrezime);
        btnImePrezime.setText("Ime i prezime");

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        btnIzbrisi.setText("Izbrisi");
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        btnIzaberi.setText("Izaberi");
        btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelZaNestajanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnJMBG)
                                .addGap(18, 18, 18)
                                .addComponent(btnImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtKriterujum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretrazi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIzaberi)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOdustani)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIzmeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIzbrisi)))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKriterujum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImePrezime)
                    .addComponent(btnJMBG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelZaNestajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnOdustani)
                    .addComponent(btnIzbrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzaberi))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
//      String kriterijum= txtKriterujum.getText(); 
//      if(kriterijum.isEmpty()){
//    
//        JOptionPane.showMessageDialog(this, "Morate uneti odovarajuci kriterijum pretrage", "Greska", JOptionPane.ERROR_MESSAGE);
//   return;
//      }
//     list=  Kontroler.getInstance().pretraziGoste(this,kriterijum);
//     if(list.isEmpty()){
//         srediFormu();
//         JOptionPane.showMessageDialog(this, "Nije pronadjen nijedan gost");
//     }
//        popuniTabelu(list);
//if(buttonGroup1.isSelected((ButtonModel) btnImePrezime)){
//kontrolerP.nadjiGostePoKriterijumu(this);
//}
if(buttonGroup1.getSelection()==btnJMBG.getModel()){
    kontrolerP.nadjiGostePoKriterijumuJMBG(this);
}
else
    kontrolerP.nadjiGostePoKriterijumu(this);
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveActionPerformed
       kontrolerP.prikaziSveGoste(this);
    }//GEN-LAST:event_btnPrikaziSveActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
      kontrolerP.izmeniGosta(this);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
kontrolerP.izbrisiGosta(this);       
    }//GEN-LAST:event_btnIzbrisiActionPerformed

    private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiActionPerformed
              
    }//GEN-LAST:event_btnIzaberiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPretragaGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPretragaGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPretragaGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPretragaGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPretragaGosta dialog = new FrmPretragaGosta(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnImePrezime;
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JRadioButton btnJMBG;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikaziSve;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelZaNestajanje;
    private javax.swing.JTable tblGosti;
    private javax.swing.JTextField txtKriterujum;
    // End of variables declaration//GEN-END:variables

    private void dodajModelTabele() {

    }

   private void setScreenCenter() {
        setLocationRelativeTo(null);
    }

    private void popuniTabelu(List<Gost> list) {
    ModelTabeleGosti mtg= new ModelTabeleGosti(list);
    tblGosti.setModel(mtg);
    mtg.fireTableDataChanged();
    }

    private void srediFormu(FrmMode mode) {
          switch (mode) {
           
            case EDIT:
                btnIzaberi.setVisible(false);
                
               break;
            case VIEW:
              btnIzbrisi.setVisible(false);
              btnIzmeni.setVisible(false);
              btnIzaberi.setVisible(true);
                break;
    }
}
}
