/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.gost;

import domain.Drzava;
import domain.Gost;
import forme.glavna.FrmGlavna;
import forme.glavna.FrmMode;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import komunikacija.Komunikacija;
import kontroler.Kontroler;
import kontroler.gost.KontrolerUnosGosta;
import transfer.Odgovor;
import transfer.Zahtev;
import transfer.util.Operacija;
import transfer.util.StatusOdgovora;

/**
 *
 * @author marij
 */
public class FrmUnosGosta extends javax.swing.JDialog {

    /**
     * Creates new form FrmUnosGosta
     */
    KontrolerUnosGosta kontrolerUnos;

    public FrmUnosGosta(FrmGlavna parent, boolean modal, FrmMode mode, Gost gost) {
        super(parent, modal);
        initComponents();
        setScreenCenter();
     //   kontrolerUnos = new KontrolerUnosGosta();
     //   kontrolerUnos.srediFormu(this);
       srediFormu(mode);
        popuniComboboxDrzava();
        kontrolerUnos= new KontrolerUnosGosta();
        kontrolerUnos.setGost(gost);
        kontrolerUnos.srediFormu(this);
      //kontrolerUnos.setGost(g);
//        kontrolerUnos.srediFormu();
    }

    public JComboBox<Object> getCmbDrzave() {
        return cmbDrzave;
    }

    public void setCmbDrzave(JComboBox<Object> cmbDrzave) {
        this.cmbDrzave = cmbDrzave;
    }

    public FrmUnosGosta(FrmGlavna aThis, boolean b, Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtImePrezime = new javax.swing.JTextField();
        txtJMBG = new javax.swing.JTextField();
        txtKontakt = new javax.swing.JTextField();
        cmbDrzave = new javax.swing.JComboBox();
        btnDodaj = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Ime i prezime: ");

        jLabel2.setText("JMBG: ");

        jLabel3.setText("Kontakt telefon: ");

        jLabel4.setText("Drzava: ");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtImePrezime)
                    .addComponent(txtKontakt)
                    .addComponent(txtJMBG)
                    .addComponent(cmbDrzave, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 163, Short.MAX_VALUE)
                .addComponent(btnOdustani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDodaj))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbDrzave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnOdustani)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
//      String imePrezime=txtImePrezime.getText();
//      String jmbg=txtJMBG.getText();
//      String kontakt=txtKontakt.getText();
//      Drzava d= (Drzava) cmbDrzave.getSelectedItem();
//      int pozivniBr=d.getPozivniBroj();
//      String naziv=d.getNaziv();
//      Gost g= new Gost(-1, jmbg, imePrezime, kontakt, new Drzava(pozivniBr, naziv));
//        
            kontrolerUnos.dodajGosta(this);
        
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
       kontrolerUnos.sacuvajIzmene(this);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmUnosGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmUnosGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmUnosGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmUnosGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmUnosGosta().setVisible(true);
//            }
//        });
//    }
    private void setScreenCenter() {
        setLocationRelativeTo(null);
    }

    private void srediFormu(FrmMode mode) {
      //  popuniCombobox();
        switch (mode) {
            case NEW:
                setTitle("Unos novog gosta");
                btnIzmeni.setVisible(false);
                btnDodaj.setVisible(true);
                break;
            case EDIT:
                btnDodaj.setVisible(false);
                btnIzmeni.setVisible(true);
                setTitle("Izmena podataka o gostu");
                break;
            case VIEW:
                txtImePrezime.setEnabled(false);
                txtJMBG.setEnabled(false);
                txtKontakt.setEnabled(false);
                cmbDrzave.setEnabled(false);
                btnDodaj.setVisible(false);
                btnIzmeni.setVisible(false);
                setTitle("Pregled podataka o gostu");
                break;

        }
    }

    private void popuniCombobox() throws IOException, ClassNotFoundException, Exception {
        popuniComboboxDrzava();
    }

    private void popuniComboboxDrzava()  {
         Zahtev zahtev= new Zahtev();
        zahtev.setOperation(Operacija.UCITAJ_SVE_DRZAVE);
        try {
            Komunikacija.getInstance().posaljiZahtev(zahtev);
        
        Odgovor odg=Komunikacija.getInstance().primiOdgovor();
       
        if(odg.getStatus()==StatusOdgovora.ERROR){
            throw new Exception(odg.getPoruka());
        }
        cmbDrzave.setModel(new DefaultComboBoxModel(((List<Drzava>)odg.getData()).toArray()));
         
         } catch (Exception ex) {
            Logger.getLogger(FrmUnosGosta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JTextField getTxtJMBG() {
        return txtJMBG;
    }

    public JTextField getTxtImePrezime() {
        return txtImePrezime;
    }

    public JTextField getTxtKontakt() {
        return txtKontakt;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JComboBox cmbDrzave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtImePrezime;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtKontakt;
    // End of variables declaration//GEN-END:variables
}
